namespace Actors.Abstractions;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, UseStringEnumConverter = false,
Converters = new[] { typeof(Tools.Rfc3339DateTimeConverter), typeof(Tools.TypeAnyConverter), typeof(JsonStringEnumConverter<Dapr.Abstractions.OperationType>) })]
[JsonSerializable(typeof(ActorHostedRequest))]
[JsonSerializable(typeof(DeleteStateRequest))]
[JsonSerializable(typeof(GetStateRequest))]
[JsonSerializable(typeof(GetBulkStateRequest))]
[JsonSerializable(typeof(ReminderResponse))]
[JsonSerializable(typeof(SaveStateRequest))]
[JsonSerializable(typeof(StateResponse))]
[JsonSerializable(typeof(BulkStateResponse))]
[JsonSerializable(typeof(TimerResponse))]
// [JsonSerializable(typeof(EntityConfig), TypeInfoPropertyName = "EntityConfigTypeInfo")]
[JsonSerializable(typeof(LookupActorRequest))]
[JsonSerializable(typeof(LookupActorResponse))]
[JsonSerializable(typeof(Reminder))]
[JsonSerializable(typeof(GetReminderRequest))]
[JsonSerializable(typeof(CreateReminderRequest))]
[JsonSerializable(typeof(CreateTimerRequest))]
[JsonSerializable(typeof(DeleteReminderRequest))]
[JsonSerializable(typeof(ListRemindersRequest))]
[JsonSerializable(typeof(DeleteTimerRequest))]
[JsonSerializable(typeof(ReminderTrack))]
[JsonSerializable(typeof(TransactionalRequest))]
[JsonSerializable(typeof(TransactionalOperation))]
[JsonSerializable(typeof(TransactionalUpsert))]
[JsonSerializable(typeof(TransactionalDelete))]
internal sealed partial class JsonContext : JsonSerializerContext;