name: BrowserDemo

on:
  workflow_dispatch:
  push:
    branches: 
    - master  
    paths: 
    - 'BrowserDemo/CshtmlDemo/**'
    - '.github/workflows/BrowserDemo.yml'

jobs:
  publish-static-file:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0' ]
    env:
      working-directory: ./BrowserDemo/CshtmlDemo
      package-name: Vishel.AWS.S3.Tools
      bucketname: oneapp-assets
      keyprefix: uploaddemo
      localpath: bin/Release/net9.0/publish/wwwroot
      
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        include-prerelease: true
    - name: Install dependencies      
      run: dotnet publish -c Release
      working-directory: ${{env.working-directory}}
      
    - name: Install Vishel tools    
      run: dotnet tool install -g Vishel.AWS.S3.Tools
      working-directory: ${{env.project-directory}}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Upload
      run: dotnet vishel awss3upload ${{env.bucketname}} ${{env.keyprefix}} ${{env.localpath}}
      working-directory: ${{env.working-directory}}

