name: DotnetTools

on:
  workflow_dispatch:
  push:
    branches: 
    - master  
    paths: 
    - 'DotnetTools/AwsS3BatchUpload/**'
    - '.github/workflows/DotnetTools.yml'

jobs:
  tools-nuget:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0' ]
    env:
      working-directory: ./DotnetTools/AwsS3BatchUpload
      package-name: Vishel.AWS.S3.Tools
      
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        include-prerelease: true
    - name: Install dependencies      
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build     
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Pack NuGet package
      run: dotnet pack -c Release
      working-directory: ${{env.working-directory}}    
    - name: Publish the package to nuget.org
      run: dotnet nuget push **/${{env.package-name}}.*.nupkg -k ${{secrets.NUGET_ACCESS_TOKEN}} -s https://api.nuget.org/v3/index.json --skip-duplicate 
      
      